### ISSUE TITLE
gpt.ReadTable expects provided filehandle to be one sector in

### ISSUE THREAD

**Issue by smoser** [rekby/gpt#2]
gpt.ReadTable expects for the filehandle provided to be positioned
at the partition table offset (which is likely 512 bytes).

While it is useful in allowing the user to provide a partition table
directly without the leading LBA, it means that the simple use case
below does not work:

    fp, err := os.Open(fname)
    gptTable, err := gpt.ReadTable(fp, SECTOR_SIZE)

ReadTable *does* have a comment stating:

    // Read GPT partition
    // Have to set to first byte of GPT Header (usually start of second sector on disk)

I lost some time figuring out why my code was failing after dropping the an 'mbr.Read' that seemed unnecessary.  In reality, the mbr.Read was providing the side effect of moving the position in 1 sector and making it work.

I'd provide a pull request to simply do a 'Seek(0, 0)' but I do see the value in reading directly from the file directly as provided.  My second option would be to add a 'Read' function that took a filehandle, did a Seek(0, 0) and then called ReadTable.

What do you think?

**Comment by smoser** [comment]
Just attaching a reproduce script as I had it before figuring out the problem.

[testme.go.txt](https://github.com/rekby/gpt/files/2796653/testme.go.txt)

**Comment by rekby** [comment]
Hello smoser.

Thanks for report.

I do read table without internal skip first sector becouse it can read not only from start disk, but and from end of disk (for example for repair purpose) and direct positioning will simple without internal skip first sector.

I view two variants for your issue:
1. More good comment for gpt.ReadTable
2. Additional methos for read GPT table from disk: 
* gpt.ReadTableFromDisk(file ReadSeekSizeInterface, sectorSize int, position BeginOrEndSelector)
* or gpt.ReadTableWithSkipMBR(file io.Reader, SectorSize uint64)

I prefer first way.

What do you think about comment:
// Read GPT partition
// Have to set to first byte of GPT Header
// For read GPT from disk usually need readerSeek

?

I can't change behaviour of this methods becouse it will broke existed code.

**Comment by rekby** [comment]
I have no Seek(0,0) in mbr read becouse when I read something from file - it expect move internal pointer for readed bytes.
